pipeline{
    agent any


    stages{
        stage('init step'){
            steps{
            sh 'terraform init -no-color'
            }
        }

        stage('validate stage'){
            steps{
                sh 'terraform validate -no-color'
            }
        }

        stage('format stage'){
            steps{
                sh 'terraform fmt -no-color'
            }
        }
    }
}